<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
	//This page is a result of an autogenerated content made by running test.html with firefox.
	function domo() {
		// Binding keys
		$('*').bind('keydown', 'Ctrl+e', function assets() {
			$('#btn_edit').trigger('click');
			return false;
		});

		$('*').bind('keydown', 'Ctrl+x', function assets() {
			$('#btn_back').trigger('click');
			return false;
		});
	}

	jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
	<h1>
		Mutasi Keluar <small><?= cclang('detail', ['Mutasi Keluar']); ?> </small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class=""><a href="<?= site_url('administrator/mutasi_keluar'); ?>">Mutasi Keluar</a></li>
		<li class="active"><?= cclang('detail'); ?></li>
	</ol>
</section>
<!-- Main content -->
<section class="content">
	<div class="row">
		<div class="col-md-12">
			<div class="box box-primary">
				<div class="box-body">
					<div class="box box-widget widget-user-2">
						<div class="widget-user-header">
							<div class="widget-user-image">
								<img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
							</div>
							<h3 class="widget-user-username">Mutasi Keluar</h3>
							<h5 class="widget-user-desc">Detail Mutasi Keluar</h5>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			<div class="box box-primary">
				<div class="box-body">
					<div class="box box-widget">
						<div class="widget-user-header">
							<h4 class="widget-user-desc">Detail Mutasi Keluar</h4>
						</div>
					</div>
					<div class="form-horizontal form-step" name="form_mutasi_keluar" id="form_mutasi_keluar">
						<div class="form-group">
							<label for="content" class="col-sm-2 control-label">ID </label>

							<div class="col-sm-8">
								<span class="detail_group-mutasi_keluar_id"><?= _ent($mutasi_keluar->mutasi_keluar_id); ?></span>
							</div>
						</div>

						<div class="form-group">
							<label for="content" class="col-sm-2 control-label">Tanggal Keluar </label>

							<div class="col-sm-8">
								<span class="detail_group-mutasi_keluar_tgl_keluar"><?= _ent($mutasi_keluar->mutasi_keluar_tgl_keluar); ?></span>
							</div>
						</div>

						<div class="form-group">
							<label for="content" class="col-sm-2 control-label">Bidang </label>

							<div class="col-sm-8">
								<?= _ent($mutasi_keluar->bidang_bidang_nama); ?>
							</div>
						</div>

						<div class="form-group">
							<label for="content" class="col-sm-2 control-label">Status </label>

							<div class="col-sm-8">
								<span class="detail_group-mutasi_keluar_status"><?= _ent($mutasi_keluar->mutasi_keluar_status); ?></span>
							</div>
						</div>

						<div class="form-group">
							<label for="content" class="col-sm-2 control-label">Keterangan </label>

							<div class="col-sm-8">
								<span class="detail_group-mutasi_keluar_keterangan"><?= _ent($mutasi_keluar->mutasi_keluar_keterangan); ?></span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-6">
			<div class="box box-primary">
				<div class="box-header">
					<div class="box box-widget">
						<div class="widget-user-header">
							<h4 class="widget-user-desc">Detail Mutasi Keluar</h4>
						</div>
					</div>
				</div>
				<div class="box-body no-padding">
					<table class="table table-striped">
						<tr>
							<th style="width: 10px">#</th>
							<th>Nama Item</th>
							<th>Jumlah</th>
							<th>Satuan</th>
						</tr>
				<?php
					$no = 1;
					foreach ($detail_keluar as $item) {
				?>
					<tr>
						<td><?= $no++;?></td>
						<td><?= $item->barang_nama;?></td>
						<td><?= $item->mukeldet_jumlah;?></td>
						<td><?= join_multi_select($item->barang_satuan_id, 'satuan_barang', 'satuan_id', 'satuan_nama');?></td>
					</tr>
				<?php
					}
				?>
					</table>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<div class="box">
				<div class="box-footer">
				<?php is_allowed('mutasi_keluar_update', function() use ($mutasi_keluar){?>
					<a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit mutasi_keluar (Ctrl+e)" href="<?= site_url('administrator/mutasi_keluar/edit/'.$mutasi_keluar->mutasi_keluar_id); ?>">
						<i class="fa fa-edit"></i> <?= cclang('update', ['Mutasi Keluar']); ?> </a>
				<?php }) ?>
					<a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/mutasi_keluar/'); ?>">
						<i class="fa fa-undo"></i> <?= cclang('go_list_button', ['Mutasi Keluar']); ?></a>
			</div>
		</div>
	</div>
</section>
<!-- /.content -->

<script>
	$(document).ready(function () { });
</script>