<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
	//This page is a result of an autogenerated content made by running test.html with firefox.
	function domo() {
		// Binding keys
		$('*').bind('keydown', 'Ctrl+e', function assets() {
			$('#btn_edit').trigger('click');
			return false;
		});

		$('*').bind('keydown', 'Ctrl+x', function assets() {
			$('#btn_back').trigger('click');
			return false;
		});
	}

	jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
	<h1>
		Mutasi Masuk <small><?= cclang('detail', ['Mutasi Masuk']); ?> </small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class=""><a href="<?= site_url('administrator/mutasi_masuk'); ?>">Mutasi Masuk</a></li>
		<li class="active"><?= cclang('detail'); ?></li>
	</ol>
</section>
<!-- Main content -->
<section class="content">
	<div class="row">
		<div class="col-md-12">
			<div class="box box-primary">
				<div class="box-body">
					<div class="box box-widget widget-user-2">
						<div class="widget-user-header">

							<div class="widget-user-image">
								<img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
							</div>
							<h3 class="widget-user-username">Mutasi Masuk</h3>
							<h5 class="widget-user-desc">Detail Mutasi Masuk</h5>
							<hr>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			<div class="box box-primary">
				<div class="box-body">
					<div class="form-horizontal form-step" name="form_mutasi_masuk" id="form_mutasi_masuk">
						<div class="form-group">
							<label for="content" class="col-sm-2 control-label">ID </label>

							<div class="col-sm-8">
								<span class="detail_group-mutasi_masuk_id"><?= _ent($mutasi_masuk->mutasi_masuk_id); ?></span>
							</div>
						</div>

						<div class="form-group">
							<label for="content" class="col-sm-2 control-label">Tanggal Masuk </label>

							<div class="col-sm-8">
								<span class="detail_group-mutasi_masuk_tgl_masuk"><?= _ent($mutasi_masuk->mutasi_masuk_tgl_masuk); ?></span>
							</div>
						</div>

						<div class="form-group">
							<label for="content" class="col-sm-2 control-label">Bidang </label>

							<div class="col-sm-8">
								<?= _ent($mutasi_masuk->bidang_bidang_nama); ?>
							</div>
						</div>

						<div class="form-group">
							<label for="content" class="col-sm-2 control-label">Status </label>

							<div class="col-sm-8">
								<span class="detail_group-mutasi_masuk_status"><?= _ent($mutasi_masuk->mutasi_masuk_status); ?></span>
							</div>
						</div>

						<div class="form-group">
							<label for="content" class="col-sm-2 control-label">Keterangan </label>

							<div class="col-sm-8">
								<span class="detail_group-mutasi_masuk_keterangan"><?= _ent($mutasi_masuk->mutasi_masuk_keterangan); ?></span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		
		<div class="col-md-6">
			<div class="box box-primary">
				<div class="box-header">
					<div class="box box-widget">
						<div class="widget-user-header">
							<h4 class="widget-user-desc">Detail Mutasi Masuk</h4>
						</div>
					</div>
				</div>
				<div class="box-body no-padding">
					<table class="table table-striped">
						<tr>
							<th style="width: 10px">#</th>
							<th>Nama Item</th>
							<th>Banyaknya Item</th>
						</tr>
				<?php
					$no = 1;
					foreach (db_get_all_data('mutasi_masuk_detail', ['mumadet_masuk_id' => $mutasi_masuk->mutasi_masuk_id]) as $item) {
				?>
					<tr>
						<td><?= $no++;?></td>
						<td><?= join_multi_select($item->mumadet_barang_id, 'barang', 'barang_id', 'barang_nama');?></td>
						<td><?= $item->mumadet_jumlah.' '.join_multi_select(join_multi_select($item->mumadet_barang_id, 'barang', 'barang_id', 'barang_satuan_id'), 'satuan_barang', 'satuan_id', 'satuan_nama');?></td>
					</tr>
				<?php
					}
				?>
					</table>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<div class="box">
				<div class="box-footer">
					<?php is_allowed('mutasi_masuk_update', function() use ($mutasi_masuk){?>
					<a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit mutasi_masuk (Ctrl+e)" href="<?= site_url('administrator/mutasi_masuk/edit/'.$mutasi_masuk->mutasi_masuk_id); ?>">
						<i class="fa fa-edit"></i> <?= cclang('update', ['Mutasi Masuk']); ?> </a>
					<?php }) ?>
					<a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/mutasi_masuk/'); ?>">
						<i class="fa fa-undo"></i> <?= cclang('go_list_button', ['Mutasi Masuk']); ?></a>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- /.content -->

<script>
	$(document).ready(function () {
		(function () {
			var mutasi_masuk_bidang_id = $('.detail_group-mutasi_masuk_bidang_id');
			var mutasi_masuk_status = $('.detail_group-mutasi_masuk_status');
		})()

	});
</script>